name: aml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - h5py==3.10.0
      - higher==0.2.1
      - idna==3.4
      - numpy==1.26.2
      - ordered-set==4.1.0
      - pillow==10.1.0
      - requests==2.31.0
      - torch==1.9.0
      - torchmeta==1.8.0
      - torchvision==0.10.0
      - tqdm==4.66.1
      - typing-extensions==4.8.0
      - urllib3==2.1.0
